services:

  postgres:
    image: postgres
    container_name: postgres-db
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

  db-service:
    build:
      dockerfile: db_service/Dockerfile
    container_name: db-service
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./db_service:/app

